<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mref_panjang_kayu extends CI_Model
{

    public $table = 'ref_panjang_kayu';
    public $id = 'kode_panjang_kayu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select("kode_panjang_kayu,panjang_kayu,diameter,kd,v_per_btg");
        $this->datatables->from('v_ref_panjang_kayu');
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('pembelian/ref_panjang_kayu/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('pembelian/ref_panjang_kayu/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" id="delete" data-id="$1" href="javascript:void(0)"').'</div>', 'kode_panjang_kayu');
        return $this->datatables->generate();
    }
 
    // get data by id
    function get_by_id($id)
    {
return $this->db->query("SELECT kode_panjang_kayu,panjang_kayu,kd_bawah,kd_atas,diameter,CASE
    WHEN LENGTH(v_per_btg)=5 THEN REPLACE(CONCAT(v_per_btg, '0'), '.', ',')
    ELSE REPLACE(v_per_btg, '.', ',')
END AS v
FROM ref_panjang_kayu WHERE kode_panjang_kayu=$id")->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function ListParent(){
        return $this->db->query("SELECT kode_menu,nama_menu FROM MENU WHERE PARENT_MENU=0 ORDER BY SORT_MENU ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */