<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mref_sub_div extends CI_Model
{

    public $table = 'ref_sub_div';
    public $id = 'kd_sub_div';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kd_sub_div,nm_sub_div,nm_divisi');
        $this->datatables->from('ref_sub_div a');
        $this->datatables->join('ref_divisi b', 'a.kd_divisi=b.kd_divisi');
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('gudang/ref_sub_div/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('gudang/ref_sub_div/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" id="delete" data-id="$1" href="javascript:void(0)"').'</div>', 'kd_sub_div');
        return $this->datatables->generate();
    }
 
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function ListTable($table,$order){
        return $this->db->query("SELECT * FROM $table ORDER BY $order ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */