
<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mrekap_bm extends CI_Model
{

    public $table = 'rekap_bm_gudang';
    public $id = 'kode_supplier';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $bulan=$this->session->userdata('bulan');
        $tahun=$this->session->userdata('tahun');
        $this->datatables->select("DATE_FORMAT(tanggal, '%d-%m-%Y') as tgl,kd_barang_masuk,tanggal,no_ttb,no_spp,purchase,c.inisial,a.kd_barang,a.nm_barang,b.spesifikasi,a.jumlah,b.satuan,a.harga,(a.jumlah*a.harga) AS total");
        $this->datatables->from('tr_barang_masuk a');
        $this->datatables->join('ref_barang b', 'a.kd_barang=b.kd_barang');
        $this->datatables->join('ref_kategori c', 'b.kd_kategori=c.kd_kategori');
        $this->datatables->where("YEAR(a.tanggal)='$tahun' AND MONTH(a.tanggal)='$bulan'");
        $this->db->order_by("tanggal", "asc");

        return $this->datatables->generate();
    }
 
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function getlap($tahun,$bulan){
        return $this->db->query("SELECT DATE_FORMAT(tanggal, '%d-%m-%Y') as tgl,kd_barang_masuk,tanggal,no_ttb,no_spp,purchase,c.inisial,a.kd_barang,a.nm_barang,b.spesifikasi,a.jumlah,b.satuan,a.harga,a.jumlah*a.harga AS total
FROM tr_barang_masuk a JOIN ref_barang b ON a.kd_barang=b.kd_barang
JOIN ref_kategori c ON b.kd_kategori=c.kd_kategori
WHERE YEAR(a.tanggal)='$tahun' AND MONTH(a.tanggal)='$bulan'
ORDER BY tanggal ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */