<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mtr_barang_keluar extends CI_Model
{

    public $table = 'tr_barang_keluar';
    public $id = 'kd_barang_keluar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json_barang() {
        $date=$this->session->userdata('date');
        $this->datatables->select("inisial,satuan,a.spesifikasi,a.kd_barang_keluar,a.nm_barang,DATE_FORMAT(tanggal, '%d-%m-%Y') as tanggal,a.harga,a.jumlah,(a.harga*a.jumlah) as tot,nm_divisi,penerima,nm_alok_p,nm_alok_b");
        $this->datatables->from('tr_barang_keluar a');  
        $this->datatables->join('ref_divisi b', 'a.kd_divisi=b.kd_divisi');
        $this->datatables->join('ref_barang c', 'a.kd_barang=c.kd_barang');
        $this->datatables->join('ref_alok_p d', 'a.kd_alok_p=d.kd_alok_p');
        $this->datatables->join('ref_alok_b e', 'a.kd_alok_b=e.kd_alok_b');
        $this->datatables->join('ref_kategori f', 'c.kd_kategori=f.kd_kategori');
        $this->db->order_by("tanggal", "desc");
        $this->datatables->where("a.tanggal='$date'");
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('gudang/tr_barang_keluar/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('gudang/tr_barang_keluar/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" id="delete" data-id="$1" href="javascript:void(0)"').'</div>', 'kd_barang_keluar');
        return $this->datatables->generate();
    }
 
    function json_sukses() {
        $this->datatables->select("inisial,satuan,a.spesifikasi,a.kd_barang_keluar,a.nm_barang,DATE_FORMAT(tanggal, '%d-%m-%Y') as tanggal,a.harga,a.jumlah,(a.harga*a.jumlah) as tot,nm_divisi,penerima,nm_alok_p,nm_alok_b");
        $this->datatables->from('tr_barang_keluar a');  
        $this->datatables->join('ref_divisi b', 'a.kd_divisi=b.kd_divisi');
        $this->datatables->join('ref_barang c', 'a.kd_barang=c.kd_barang');
        $this->datatables->join('ref_alok_p d', 'a.kd_alok_p=d.kd_alok_p');
        $this->datatables->join('ref_alok_b e', 'a.kd_alok_b=e.kd_alok_b');
        $this->datatables->join('ref_kategori f', 'c.kd_kategori=f.kd_kategori');
        $this->db->order_by("tanggal", "desc");
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('gudang/tr_barang_keluar/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('gudang/tr_barang_keluar/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" onclick="javasciprt: return confirm(\'Apakah anda yakin?\')"').'</div>', 'kd_barang_keluar');
        return $this->datatables->generate();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function ListTabel($nm_tabel,$order){
        return $this->db->query("SELECT * from $nm_tabel ORDER BY $order ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */