<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mtr_mutasi_barang extends CI_Model
{

    public $table = 'tr_mutasi_barang';
    public $id = 'kd_mutasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $kd_barang=$this->session->userdata('barang');
        if($kd_barang!="all")
        {
        $this->datatables->select('kd_mutasi,kd_barang,nm_barang,stok_awal,masuk,keluar, saldo,bulan,tahun');
        $this->datatables->from('tr_mutasi_barang');
        $this->datatables->where("kd_barang=$kd_barang");
        $this->db->order_by("nm_barang", "asc");
        return $this->datatables->generate();
        }
        else{
        $this->datatables->select('kd_mutasi,kd_barang,nm_barang,stok_awal,masuk,keluar, saldo,bulan,tahun');
        $this->datatables->from('tr_mutasi_barang');
        $this->db->order_by("nm_barang", "asc");
        return $this->datatables->generate();
        }
    }
 
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function ListBarang(){
        return $this->db->query("SELECT * FROM ref_barang  ORDER BY nm_barang ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */