<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mtr_barang_keluar extends CI_Model
{

    public $table = 'tr_barang_keluar';
    public $id = 'kd_barang_keluar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json_barang() {
        $date=$this->session->userdata('date');
        $this->datatables->select("kd_barang_keluar,nm_barang,DATE_FORMAT(tanggal, '%d-%m-%Y') as tanggal,harga,jumlah,nm_unit");
        $this->datatables->from('tr_barang_keluar a');  
        $this->datatables->join('ref_unit b', 'a.kd_unit=b.kd_unit');
        $this->db->order_by("tanggal", "desc");
        $this->datatables->where("a.tanggal='$date'");
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('gudang/tr_barang_keluar/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('gudang/tr_barang_keluar/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" onclick="javasciprt: return confirm(\'Apakah anda yakin?\')"').'</div>', 'kd_barang_keluar');
        return $this->datatables->generate();
    }
 
    function json_sukses() {
        $this->datatables->select("kd_barang_keluar,nm_barang,DATE_FORMAT(tanggal, '%d-%m-%Y') as tanggal,harga,jumlah,nm_unit");
        $this->datatables->from('tr_barang_keluar_log a');  
        $this->datatables->join('ref_unit b', 'a.kd_unit=b.kd_unit');
        $this->db->order_by("tanggal", "desc");
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('gudang/tr_barang_keluar/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('gudang/tr_barang_keluar/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" onclick="javasciprt: return confirm(\'Apakah anda yakin?\')"').'</div>', 'kd_barang_keluar');
        return $this->datatables->generate();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function ListBarang(){
        return $this->db->query("SELECT * from ref_barang ORDER BY nm_barang ASC")->result();
    }
    function ListUnit(){
        return $this->db->query("SELECT * from ref_unit ORDER BY nm_unit ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */