<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mmenu extends CI_Model
{

    public $table = 'MENU';
    public $id = 'KODE_MENU';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select("kode_menu,
          nama_menu,
          parent_menu,
          active");
        $this->datatables->from("(SELECT KODE_MENU,
                  NAMA_MENU,
                  CASE PARENT_MENU WHEN 0 THEN '#' ELSE NULL END AS PARENT_MENU,
                  CASE ACTIVE WHEN '1' THEN 'Aktif' ELSE 'Non Aktif' END
                     AS ACTIVE
             FROM MENU a
            WHERE PARENT_MENU = '0'
           UNION
           SELECT a.KODE_MENU,
                  a.NAMA_MENU,
                  b.NAMA_MENU PARENT,
                  CASE ACTIVE WHEN '1' THEN 'Aktif' ELSE 'Non Aktif' END
                     AS active
             FROM MENU a, (SELECT KODE_MENU, NAMA_MENU FROM MENU) b
            WHERE a.PARENT_MENU = b.KODE_MENU)c");
        //add this line for join
        //$this->datatables->join('table2', 'p_menu.field = table2.field');
        // $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('Setting/Msmenu/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-success"').anchor(site_url('Setting/Msmenu/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" onclick="javasciprt: return confirm(\'Apakah anda yakin?\')"').'</div>', 'KODE_MENU');\
        $this->datatables->add_column('action', '<div class="btn-group">'.anchor(site_url('Setting/Msmenu/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-xs btn-danger" onclick="javasciprt: return confirm(\'Apakah anda yakin?\')"').'</div>', 'kode_menu');
        return $this->datatables->generate();
    }
 
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function ListParent(){
        return $this->db->query("SELECT kode_menu,nama_menu FROM MENU WHERE PARENT_MENU=0 ORDER BY SORT_MENU ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 05:30:09 */
/* http://harviacode.com */