<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mmenu extends CI_Model
{

    public $table = 'ms_menu';
    public $id = 'id_inc';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        // SELECT id_inc,nama_menu,parent,sort FROM v_menu
        $this->datatables->select('id_inc,nama_menu,parent,sort');
        $this->datatables->from('v_menu');
        $this->datatables->add_column('action','<div class="btn-group">'.anchor(site_url('msmenu/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-primary"').anchor(site_url('msmenu/delete/$1'),'<i class="fa fa-trash"></i>','onclick="javasciprt: return confirm(\'Apakah anda yakin?\')" class="btn btn-xs btn-danger"' ).'</div>', 'id_inc');
        return $this->datatables->generate();
    }

   

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getParent(){
        return $this->db->query("SELECT '0' id_inc,'Parent' nama_menu,0 sort
                                UNION 
                                SELECT id_inc,nama_menu,sort
                                FROM ms_menu a  WHERE  parent=0
                                ORDER BY sort ASC")->result();
    }

}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-25 04:10:06 */
/* http://harviacode.com */