<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mrole extends CI_Model
{

    public $table = 'ms_role';
    public $id = 'id_inc';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_inc,nama_role');
        $this->datatables->from('ms_role');
        //add this line for join
        //$this->datatables->join('table2', 'ms_role.field = table2.field');
        $this->datatables->add_column('action','<div class="btn-group">'.anchor(site_url('role/update/$1'),'<i class="fa fa-edit"></i>','class="btn btn-xs btn-primary"').anchor(site_url('role/delete/$1'),'<i class="fa fa-trash"></i>','onclick="javasciprt: return confirm(\'Apakah anda yakin?\')" class="btn btn-xs btn-danger"' ).'</div>', 'id_inc');
        return $this->datatables->generate();
    }

   

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mrole.php */
/* Location: ./application/models/Mrole.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-25 04:03:38 */
/* http://harviacode.com */